echo Downloading charm...
sudo wget -N raw.github.com/vandeurenglenn/charm/preview/charm --quiet
sudo chmod +x charm
echo Installing charm...
sudo mv ./charm /usr/bin/charm
echo Installation complete.
