echo Downloading charm...
sudo wget -N raw.github.com/vandeurenglenn/charm/master/charm --quiet
sudo chmod +x charm
echo Installing charm...
sudo mv ./charm /usr/local/bin/charm
echo Installation complete.
